import { useMemo, useState } from 'react'
import { assetUrl } from '../lib/assetUrl.js'
import { approvedIconRegion, designColors, designSections, marketExamples, matrixRegions } from '../data/designSystem.js'
import PageShell from './PageShell.jsx'
import BrandRegion from './BrandRegion.jsx'
import SpecificationVisual from './SpecificationVisual.jsx'

function Section({ id, children, className = '' }) {
  const [, number, title] = designSections.find(section => section[0] === id)
  return <section id={id} className={`hz-matrix-section ${className}`} data-design-section={id}><h2><span>{number}.</span> {title}</h2>{children}</section>
}
function Sparkline({ variant = 'line' }) {
  const points = '2,52 9,50 16,52 23,44 30,46 37,41 44,44 51,34 58,39 65,31 72,36 79,24 86,29 93,26 100,35 107,29 114,19 121,23 128,14 135,20 142,11 149,15 156,4'
  return <svg className={`hz-mini-chart hz-chart-${variant}`} viewBox="0 0 158 58" role="img" aria-label={`Illustrative ${variant} market trend`}><title>Illustrative market trend, not a live feed</title>{variant === 'area' && <polygon points={`2,58 ${points} 156,58`} fill="currentColor" opacity=".16" />}{variant === 'bars' ? Array.from({ length: 30 }, (_, i) => <path key={i} d={`M${3 + i * 5} 56v-${8 + (i * 13) % 43}`} stroke="currentColor" strokeWidth="2" />) : <polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.3" />}</svg>
}
function MarketCard({ market, dark = false }) { return <article className={`hz-market-card ${dark ? 'hz-example-dark' : 'hz-example-light'}`}><header><div><strong>{market.name}</strong><small>{market.venue}</small></div><span className="hz-dot" /></header><div className="hz-market-price">{market.value}<small>{market.unit}</small></div><span className={market.up ? 'hz-positive' : 'hz-negative'}>{market.movement}</span><Sparkline /></article> }
function Watchlist({ dark = false }) { return <div className={`hz-watchlist ${dark ? 'hz-example-dark' : 'hz-example-light'}`}>{marketExamples.map(market => <div key={market.name}><span><strong>{market.name}</strong><small>{market.venue}</small></span><span>{market.value}</span><small className={market.up ? 'hz-positive' : 'hz-negative'}>{market.movement}</small></div>)}</div> }

export default function DesignSystemPage() {
  const [filter, setFilter] = useState('All')
  const [query, setQuery] = useState('')
  const [live, setLive] = useState(true)
  const [feedback, setFeedback] = useState('Select a specimen to inspect its state.')
  const [range, setRange] = useState('1M')
  const results = useMemo(() => ['Copper supply insight', 'Gold market research', 'Latest transcript', 'Strategy hypothesis', 'Meeting preparation'].filter(item => item.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || item.toLowerCase().includes(filter.toLowerCase().replace('transcripts', 'transcript').replace('markets', 'market')))), [filter, query])
  return <PageShell current="design-system">
    <section className="hz-matrix-hero"><img src={assetUrl('/brand/hazine-wordmark.png')} alt="Approved Hazine primary wordmark" /><div><small>BRAND SYSTEM / DESIGN MATRIX</small><h1>Living treasury<br /><em>of market intelligence.</em></h1><p>The approved visual system, rebuilt as readable, responsive components.</p></div><BrandRegion region={matrixRegions.glyph} label="Approved primary glyph from the immutable source matrix" /></section>
    <nav className="hz-matrix-directory" aria-label="Design matrix sections">{designSections.map(([id, number, title]) => <a href={`#${id}`} key={id}><small>{number}</small>{title}</a>)}</nav>
    <div className="hz-matrix-grid">
      <Section id="logo-system" className="hz-logo-section"><div className="hz-logo-specimens"><figure><figcaption>Primary wordmark</figcaption><img src={assetUrl('/brand/hazine-wordmark.png')} alt="Approved sweeping-Z wordmark artwork" /></figure><figure><figcaption>Primary glyph / monogram</figcaption><BrandRegion region={matrixRegions.glyph} label="Actual approved Hazine glyph — source matrix display" /></figure><figure><figcaption>Primary lockup</figcaption><img src={assetUrl('/brand/hazine-lockup.png')} alt="Approved glyph and wordmark lockup artwork" /></figure></div><p className="hz-matrix-note">Artwork, never typography. Original files remain unchanged. Glyph shown from the approved matrix; standalone production master remains an explicit asset gap.</p></Section>
      <Section id="app-icons"><div className="hz-icon-specimens">{[['production', 'Production icon'], ['subtle', 'Subtle variation'], ['circular', 'Circular framed'], ['special', 'Modern glassmorphic']].map(([key, label]) => <figure key={key}><BrandRegion region={matrixRegions[key]} label={`Approved ${label} — actual matrix artwork`} /><figcaption>{label}</figcaption></figure>)}</div><p className="hz-matrix-note">Approved explorations, not newly generated icons. Each specimen isolates its actual matrix artwork; the PDF’s wider icon-source crop is preserved separately in the specification. Production master export is still required.</p></Section>
      <Section id="color-system"><div className="hz-color-specimens">{designColors.map(([name, color]) => <button key={name} type="button" onClick={() => setFeedback(`${name}: ${color}. Token selected.`)} aria-label={`Inspect ${name}, ${color}`}><i style={{ backgroundColor: color }} /><strong>{name}</strong><code>{color}</code></button>)}</div></Section>
      <Section id="typography"><div className="hz-type-pair"><div><small>DISPLAY SERIF (BRAND)</small><p className="hz-cinzel-specimen">Market Intelligence</p><span>Cinzel · artwork is not a font</span><p className="hz-alphabet">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br />0123456789</p></div><div><small>UI SANS (INTERFACE)</small><p className="hz-inter-specimen">Inter</p><span>Precise, calm, readable</span><p className="hz-alphabet">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br />abcdefghijklmnopqrstuvwxyz<br />0123456789</p></div></div><div className="hz-type-scale">{[['H1', 'Headline', '36 / 44'], ['H2', 'Subheadline', '24 / 32'], ['H3', 'Section title', '18 / 24'], ['SUBHEAD', 'Label / Subhead', '14 / 20'], ['BODY', 'Body text', '14 / 20'], ['CAPTION', 'Caption text', '12 / 16']].map(([label, text, size]) => <div key={label}><small>{label}</small><span>{text}</span><code>{size}</code></div>)}</div></Section>
      <Section id="component-system" className="hz-wide-section"><p className="hz-matrix-note">Interactive specimens · market numbers and transcript content below are illustrative matrix/demo values, not live data.</p><div className="hz-component-controls"><div><small>BUTTONS</small><button type="button" className="hz-primary" onClick={() => setFeedback('Primary action confirmed. The source remains attached.')}>Primary</button><button type="button" className="hz-secondary" onClick={() => setFeedback('Secondary action selected.')}>Secondary</button><button type="button" className="hz-tertiary" onClick={() => setFeedback('Treasury specimen opened.')}>Treasury ↗</button></div><div><small>PILLS / TAGS</small><div className="hz-filter-pills" role="group" aria-label="Filter vault examples">{['All', 'Markets', 'Research', 'Transcripts', 'Strategy', 'Meeting'].map(label => <button type="button" aria-pressed={filter === label} key={label} onClick={() => setFilter(label)}>{label}</button>)}</div></div><div><small>SEARCH</small><label className="hz-vault-search"><span aria-hidden="true">⌕</span><input aria-label="Search vault specimen" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search Hazine Vault…" /><kbd>⌘ K</kbd></label><div className="hz-vault-results" role="status">{results.length ? results.slice(0, 2).join(' · ') : 'No matching specimens'}</div></div><div><small>SIGNAL CHIPS</small>{[['Copper', 'Supply signal', 'High'], ['Gold', 'Macro signal', 'Medium'], ['Crude oil', 'Geopolitical signal', 'High']].map(([market, text, severity]) => <button type="button" className="hz-signal-chip" key={market} onClick={() => setFeedback(`${market}: ${text}. Severity ${severity}. Illustrative example.`)}><strong>{market}</strong><span>{text}</span><em>{severity}</em></button>)}</div><div><small>PANEL HEADER</small><button type="button" className="hz-panel-header" onClick={() => setFeedback('Live signals panel selected; 3 illustrated signals.')}>⌁ <strong>LIVE SIGNALS</strong><span>View all signals →</span></button></div></div>
        <div className="hz-market-examples"><div><small>MARKET CARD (LIGHT)</small><MarketCard market={marketExamples[0]} /></div><div><small>MARKET CARD (DARK)</small><MarketCard market={marketExamples[1]} dark /></div><div><small>WATCHLIST ROW (LIGHT)</small><Watchlist /></div><div><small>WATCHLIST ROW (DARK)</small><Watchlist dark /></div><div className="hz-chart-examples"><small>MINI CHARTS</small><div>{['line', 'area', 'bars'].map(variant => <figure key={variant}><figcaption>{variant}</figcaption><Sparkline variant={variant} /></figure>)}</div></div></div>
        <div className="hz-glass-examples"><div><small>GLASS CARD (LIGHT)</small><article className="hz-glass-card hz-example-light"><header><strong>COPPER TIGHTNESS</strong><span className="hz-dot" /></header><p>High Confidence</p><div className="hz-insight-network"><i>Cu</i>{Array.from({ length: 8 }, (_, i) => <span key={i} style={{ '--angle': `${i * 45}deg` }} />)}</div><span className="hz-status required">INTERPRETATION · DEMO</span></article></div><div><small>GLASS CARD (DARK)</small><article className="hz-glass-card hz-example-dark"><header><strong>LATEST TRANSCRIPT INSIGHT</strong></header><p>“We continue to see strong demand from China and limited new supply through Q3.”</p><small>Demo excerpt · Head of commercial</small><button type="button" className="hz-evidence-play" onClick={() => setFeedback('Illustrative transcript moment selected: 00:28. No live recording is implied.')}>▷ <span>00:28</span><Sparkline /></button></article></div><div><small>STATUS BADGES</small><div className="hz-status-panel hz-example-dark"><span><i className="hz-dot" />{live ? 'Live' : 'Paused'}<small>Illustrative state</small></span><span>◇ Verified<small>Provenance</small></span><span>⬡ High confidence<small>Model score 0.82 · demo</small></span></div><div className="hz-epistemic-tags">{['FACT', 'SIGNAL', 'INTERPRETATION', 'HYPOTHESIS', 'STRATEGY'].map(type => <span key={type} data-taxonomy={type}>{type}</span>)}</div></div><div><small>DATA BADGES</small><div className="hz-data-badges">{[['LME inventory', 'Source'], ['China import', 'Indicator'], ['Smelter outage', 'Event'], ['Policy signal', 'Macro']].map(([title, type]) => <button type="button" key={title} onClick={() => setFeedback(`${title} · ${type}. Evidence badge inspected.`)}><span>◇</span><strong>{title}<small>{type}</small></strong></button>)}</div></div><div><small>TOGGLE / INPUTS</small><label className="hz-toggle"><input type="checkbox" role="switch" checked={live} onChange={event => setLive(event.target.checked)} /><span />Follow live signals</label><label className="hz-select-label">Market<select aria-label="Choose market specimen" onChange={event => setFeedback(`${event.target.value} market specimen selected.`)}>{marketExamples.map(market => <option key={market.name}>{market.name}</option>)}</select></label><label className="hz-select-label">Observation date<input type="date" defaultValue="2026-08-24" /></label><div className="hz-range-buttons" role="group" aria-label="Market range">{['1D', '1W', '1M', '1Y', 'ALL'].map(label => <button type="button" key={label} aria-pressed={range === label} onClick={() => { setRange(label); setFeedback(`${label} range selected.`) }}>{label}</button>)}</div></div></div><p className="hz-specimen-feedback" role="status">{feedback}</p></Section>
      <Section id="layout-language"><div className="hz-layout-specimen"><aside><small>LEFT RAIL (DARK)</small>{['Home', 'Markets', 'Research', 'Video', 'Conversations', 'Atlas', 'Strategy'].map((label, i) => <span key={label} className={i === 1 ? 'active' : ''}>◫ {label}</span>)}<strong>Hazine Vault</strong></aside><div><small>PRIMARY WORKSPACE (LIGHT)</small><h3>Intelligence Brief</h3><p>What changed. Why it matters.</p><div className="hz-layout-lines"><i /><i /><i /></div><div className="hz-layout-cards"><Sparkline /><Sparkline variant="area" /></div><h4>Connected insights</h4><div className="hz-layout-lines"><i /><i /></div></div><aside><small>RIGHT RAIL (DARK)</small><strong>Live signals</strong><span>Copper · supply</span><span>Gold · macro</span><strong>Watchlist</strong><span>Market context</span><strong>Meeting prep</strong><span>20 minutes</span></aside></div><div className="hz-regime-strip">REGIME · SENTIMENT · LIQUIDITY · THOUGHT</div></Section>
      <Section id="product-surfaces"><div className="hz-surface-specimens"><figure><figcaption>Desktop application · approved reference</figcaption><img loading="lazy" src={assetUrl('/brand/hazine-desktop-v4.png')} alt="Approved bright-center dark-rails Hazine desktop" /><a href={assetUrl('/workbench/')}>Inspect shared live state →</a></figure><figure><figcaption>Claude plugin / Hazine sidecar · approved reference</figcaption><img loading="lazy" src={assetUrl('/brand/hazine-claude-plugin-v4.png')} alt="Approved Claude plugin dark Hazine sidecar" /><a href={assetUrl('/specification/#section-04')}>Read surface contracts →</a></figure></div></Section>
      <Section id="iconography" className="hz-wide-section"><div className="hz-iconography-row"><BrandRegion region={matrixRegions.motifs} label="Approved iconography and visual motifs from the original matrix — not redrawn" /><div><h3>Knowledge has a visual language.</h3><p>Intelligence · Knowledge · Signals · Markets · Treasury · Provenance · Strategy · Network · Security · Document · Compass</p><p className="hz-matrix-note">Display-only source artwork. A standalone, accessible production icon set is not present in the supplied assets; no replacement symbols are claimed as canonical.</p></div></div><SpecificationVisual kind="epistemic" sourceLine={214} /></Section>
    </div>
  </PageShell>
}
