const definitions = {
  pipeline: { title: 'Collect → Connect → Surface', note: 'Each authored transformation retains its source locator.', nodes: [['INGEST', 'Video · calls · feeds · notes'], ['NORMALIZE', 'Transcript + metadata'], ['EXTRACT', 'Entities · claims · signals'], ['CONNECT', 'Graph + relationships'], ['MEMORIZE', 'Evidence + provenance'], ['SURFACE', 'Briefs · prep · alerts · recall']] },
  architecture: { title: 'One intelligence core, two surfaces', note: 'Sources normalize into Hazine Core. Desktop and plugin consume shared contracts, not separate knowledge systems.', nodes: [['SOURCES', 'Markets · news · video · research · calls · notes'], ['HAZINE CORE', 'Ingestion · intelligence · memory + graph · provenance · retrieval'], ['DESKTOP', 'Explore · compare · strategize'], ['PLUGIN', 'Brief · retrieve · deep-link']] },
  surfaces: { title: 'Depth in Hazine; aperture in the agent', note: 'Both surfaces share identity, memory and capabilities. The plugin deep-links exact desktop context.', nodes: [['DESKTOP / DEEP WORK', 'Explore · compare evidence · inspect memory · build strategy'], ['ONE CORE', 'Identity · memory · contracts'], ['PLUGIN / IN-FLOW', 'Brief · signals · sources · exact desktop state']] },
  epistemic: { title: 'Evidence → inference → strategy', note: 'The specification’s copper example. Supporting evidence does not turn inference into fact.', nodes: [['FACT', 'Market price · directly observed'], ['SIGNAL', 'Declining inventory · measured pattern'], ['INTERPRETATION', 'Supply is tightening · inferred meaning'], ['HYPOTHESIS', 'Premiums rise next month · testable expectation'], ['STRATEGY', 'Raise delivery optionality · Ezgi’s possible move']] },
  memory: { title: 'Evidence remains attached as memory compounds', note: 'Pin · Correct · Merge · Forget · Reclassify · Trace. Required user controls, not claims that the demo implements all operations.', nodes: [['OBSERVATION', 'Source + time · raw evidence'], ['ASSERTION', 'Taxonomy + confidence'], ['MEMORY', 'Versioned + inspectable'], ['RECALL', 'Contextual surface']] },
  roadmap: { title: 'Trust infrastructure before compounding intelligence', note: 'Product-source phased delivery. A roadmap, not a completed-release ledger.', nodes: [['01 FOUNDATION', 'Core schema · provenance · search'], ['02 DESKTOP', 'Home · markets · research · Atlas'], ['03 INGESTION', 'Video · transcript · comparison'], ['04 LIVE', 'Calls · calendar · meeting prep'], ['05 PLUGIN', 'Claude sidecar · deep links'], ['06 COMPOUND', 'Outcomes · source quality · learning']] },
  layout: { title: 'Canonical three-zone composition', note: 'Dark rails frame a luminous center. The regime strip remains ambient.', nodes: [['DARK LEFT RAIL', 'Persistent navigation · Vault · mineral ornament'], ['LIGHT CENTER WORKSPACE', 'Narrative brief · market overview · connected insights · Atlas'], ['DARK RIGHT RAIL', 'Live signals · watchlist · meeting prep']] },
}
function Arrow({ label }) { return <svg className="hz-flow-arrow" viewBox="0 0 50 30" role="img" aria-label={label}><path d="M3 15H43M35 7L43 15L35 23" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg> }
function Node({ definition, index, kind }) {
  const [title, body] = definition.nodes[index]
  return <div className={`hz-flow-node hz-node-${index}`}><small>{kind === 'epistemic' ? ['EVIDENCE', 'EVIDENCE', 'INFERENCE', 'INFERENCE', 'ACTION'][index] : String(index + 1).padStart(2, '0')}</small><strong>{title}</strong><p>{body}</p></div>
}
export default function SpecificationVisual({ kind, sourceLine }) {
  const definition = definitions[kind]
  if (!definition) return null
  return <figure className={`hz-spec-visual hz-visual-${kind}`} data-source-line={sourceLine}>
    <header><small>SOURCE-BACKED VISUAL · REQUIREMENT</small><h3>{definition.title}</h3></header>
    {kind === 'architecture' ? <div className="hz-architecture-wiring"><Node definition={definition} index={0} kind={kind} /><Arrow label="Sources normalize into Hazine Core" /><Node definition={definition} index={1} kind={kind} /><svg className="hz-core-branches" viewBox="0 0 60 180" role="img" aria-label="Hazine Core branches independently to desktop and plugin through shared contracts"><path d="M0 90H24V40H55M47 32L55 40L47 48M24 90V140H55M47 132L55 140L47 148" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg><div className="hz-architecture-surfaces"><Node definition={definition} index={2} kind={kind} /><Node definition={definition} index={3} kind={kind} /></div></div> : <div className="hz-flow-nodes">{definition.nodes.map(([title], index) => <div className="hz-flow-unit" key={title}><Node definition={definition} index={index} kind={kind} />{index < definition.nodes.length - 1 && <Arrow label={kind === 'surfaces' ? 'Shared core read/write, exact-context deep-link' : 'Source-preserving transformation'} />}</div>)}</div>}
    {kind === 'layout' && <div className="hz-regime-strip">MARKET REGIME · SENTIMENT · LIQUIDITY · HAZINE THOUGHT</div>}
    <figcaption>{definition.note}<span> Authored diagram: build_hazine_pdf.py · document call line {sourceLine}.</span></figcaption>
  </figure>
}
