/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\digit\Documents\Codex\2026-09-01\referenced-chatgpt-conversation-this-is-an\work\hazine-experience\public\models\business_call.glb --output C:\Users\digit\Documents\Codex\2026-09-01\referenced-chatgpt-conversation-this-is-an\work\hazine-experience\src\models\BusinessCallModel.jsx --keepnames --meta --shadows --root public 
Author: Grauwolf (https://sketchfab.com/Grauwolf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/business-call-6b386c234c9b4a30af30bf2408d0aaa9
Title: Business Call
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/business_call.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_4" castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.material_0} position={[0, 0, -0.002]} scale={0.952} userData={{ name: 'Object_4' }} />
    </group>
  )
}

useGLTF.preload('/models/business_call.glb')
