/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\sky_blue_crystal.glb --output src\models\CrystalModel.jsx --keepnames --meta --shadows --root public 
Author: Zambur (https://sketchfab.com/Zambur)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sky-blue-crystal-8dbb4fcf62314592b2c55ca556a69d23
Title: Sky blue crystal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { modelUrl } from '../lib/assetManifest.js'

const MODEL_URL = modelUrl('crystal')

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.CristalesinitialShadingGroup} position={[0.516, 0.414, -0.208]} rotation={[-Math.PI / 2, 0, 0]} scale={5.221} userData={{ name: 'Object_2' }} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
