/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\caterpillar_797f_mining_truck.glb --output src\models\MiningTruckModel.jsx --keepnames --meta --shadows --root public 
Author: tpersohn (https://sketchfab.com/tpersohn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/caterpillar-797f-mining-truck-dZM64cBYmcGvXfIPfctL7VYthzj
Title: Caterpillar 797F Mining Truck
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { modelUrl } from '../lib/assetManifest.js'

const MODEL_URL = modelUrl('truck')

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.mia_material1SG} position={[-1.756, 11.91, 1.138]} rotation={[-Math.PI / 2, 0, 0]} scale={26.398} userData={{ name: 'Object_2' }} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
