/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\digit\Documents\Codex\2026-09-01\referenced-chatgpt-conversation-this-is-an\work\hazine-experience\public\models\free__atlanta_corperate_office_building.glb --output C:\Users\digit\Documents\Codex\2026-09-01\referenced-chatgpt-conversation-this-is-an\work\hazine-experience\src\models\OfficeBuildingModel.jsx --keepnames --meta --shadows --root public 
Author: 99.Miles (https://sketchfab.com/99.Miles)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-atlanta-corperate-office-building-d96380fb001345cca9a9be121f3e43d5
Title: [FREE]  Atlanta, Corperate Office Building
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/free__atlanta_corperate_office_building.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Cube009_Lobby_Interior_Baked_0" castShadow receiveShadow geometry={nodes.Cube009_Lobby_Interior_Baked_0.geometry} material={materials.Lobby_Interior_Baked} position={[26.652, 18.477, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={44.684} userData={{ name: 'Cube.009_Lobby Interior Baked_0' }} />
      <mesh name="Cube001_Windows_0" castShadow receiveShadow geometry={nodes.Cube001_Windows_0.geometry} material={materials.Windows} position={[26.652, 117.239, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={88.572} userData={{ name: 'Cube.001_Windows_0' }} />
      <mesh name="Cube002_Material_0" castShadow receiveShadow geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} position={[27.413, 114.133, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={105.999} userData={{ name: 'Cube.002_Material_0' }} />
      <mesh name="Cube003_Blinds_0" castShadow receiveShadow geometry={nodes.Cube003_Blinds_0.geometry} material={materials.Blinds} position={[26.612, 107.411, -46.806]} rotation={[-Math.PI / 2, 0, 0]} scale={98.401} userData={{ name: 'Cube.003_Blinds_0' }} />
      <mesh name="Cube004_Billboard_0" castShadow receiveShadow geometry={nodes.Cube004_Billboard_0.geometry} material={materials.Billboard} position={[57.829, 213.263, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={46.273} userData={{ name: 'Cube.004_Billboard_0' }} />
      <mesh name="Cube005_Glass_0" castShadow receiveShadow geometry={nodes.Cube005_Glass_0.geometry} material={materials.Glass} position={[26.652, 117.239, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={88.572} userData={{ name: 'Cube.005_Glass_0' }} />
      <mesh name="Cube006_Emmisive_0" castShadow receiveShadow geometry={nodes.Cube006_Emmisive_0.geometry} material={materials.Emmisive} position={[26.652, 213.947, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={47.488} userData={{ name: 'Cube.006_Emmisive_0' }} />
      <mesh name="Cube007_Glass_Lobby_0" castShadow receiveShadow geometry={nodes.Cube007_Glass_Lobby_0.geometry} material={materials.Glass_Lobby} position={[26.958, 16.972, -46.805]} rotation={[-Math.PI / 2, 0, 0]} scale={44.476} userData={{ name: 'Cube.007_Glass Lobby_0' }} />
      <mesh name="Cube008__0" castShadow receiveShadow geometry={nodes.Cube008__0.geometry} material={materials['Cube.008__0']} position={[54.398, 9.333, -51.049]} rotation={[-Math.PI / 2, 0, 0]} scale={1.189} userData={{ name: 'Cube.008__0' }} />
      <mesh name="Cube010_Bulb_0" castShadow receiveShadow geometry={nodes.Cube010_Bulb_0.geometry} material={materials.Bulb} position={[26.653, 19.892, -46.823]} rotation={[-Math.PI / 2, 0, 0]} scale={48.248} userData={{ name: 'Cube.010_Bulb_0' }} />
      <mesh name="Cube011_Lobby_Interior_Trimsheet_0" castShadow receiveShadow geometry={nodes.Cube011_Lobby_Interior_Trimsheet_0.geometry} material={materials.Lobby_Interior_Trimsheet} position={[20.232, 26.466, -35.418]} rotation={[-Math.PI / 2, 0, 0]} scale={35.653} userData={{ name: 'Cube.011_Lobby Interior Trimsheet_0' }} />
      <mesh name="Cube012_Parralax_Mapping_0" castShadow receiveShadow geometry={nodes.Cube012_Parralax_Mapping_0.geometry} material={materials.Parralax_Mapping} position={[26.652, 117.239, -46.807]} rotation={[-Math.PI / 2, 0, 0]} scale={88.572} userData={{ name: 'Cube.012_Parralax Mapping_0' }} />
    </group>
  )
}

useGLTF.preload('/models/free__atlanta_corperate_office_building.glb')
