/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\digit\Documents\Codex\2026-09-01\referenced-chatgpt-conversation-this-is-an\work\hazine-experience\public\models\minimalistic_modern_office.glb --output C:\Users\digit\Documents\Codex\2026-09-01\referenced-chatgpt-conversation-this-is-an\work\hazine-experience\src\models\OfficeModel.jsx --keepnames --meta --shadows --root public 
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minimalistic-modern-office-5540183da1c7452f810f8de33734879a
Title: Minimalistic Modern Office
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/minimalistic_modern_office.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Minimalistic_Modern_Office_Glass_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Glass_0.geometry} material={materials.Glass} position={[2.406, 0.706, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[2.417, 7.25, 2.417]} userData={{ name: 'Minimalistic Modern Office_Glass_0' }} />
      <mesh name="Minimalistic_Modern_Office_Structure_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Structure_0.geometry} material={materials.Structure} position={[4.586, 0.706, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[4.597, 13.79, 4.597]} userData={{ name: 'Minimalistic Modern Office_Structure_0' }} />
      <mesh name="Minimalistic_Modern_Office_Background_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Background_0.geometry} material={materials.Background} position={[1.499, 1.245, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[5.425, 16.274, 5.425]} userData={{ name: 'Minimalistic Modern Office_Background_0' }} />
      <mesh name="Minimalistic_Modern_Office_Table_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Table_0.geometry} material={materials.Table} position={[3.885, -1.043, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.424, 1.272, 0.424]} userData={{ name: 'Minimalistic Modern Office_Table_0' }} />
      <mesh name="Minimalistic_Modern_Office_Chair_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Chair_0.geometry} material={materials.Chair} position={[3.121, -0.85, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.598, 1.795, 0.598]} userData={{ name: 'Minimalistic Modern Office_Chair_0' }} />
      <mesh name="Minimalistic_Modern_Office_Plants_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Plants_0.geometry} material={materials.Plants} position={[0.508, -0.447, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.484, 4.451, 1.484]} userData={{ name: 'Minimalistic Modern Office_Plants_0' }} />
      <mesh name="Minimalistic_Modern_Office_Lights_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_Lights_0.geometry} material={materials.Lights} position={[2.472, 1.766, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.272, 3.815, 1.272]} userData={{ name: 'Minimalistic Modern Office_Lights_0' }} />
      <mesh name="Minimalistic_Modern_Office_LightEmission_0" castShadow receiveShadow geometry={nodes.Minimalistic_Modern_Office_LightEmission_0.geometry} material={materials.LightEmission} position={[2.472, 1.766, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.256, 3.767, 1.256]} userData={{ name: 'Minimalistic Modern Office_LightEmission_0' }} />
      <mesh name="Carpet_Carpet_0" castShadow receiveShadow geometry={nodes.Carpet_Carpet_0.geometry} material={materials.Carpet} position={[3.532, -1.444, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.013} userData={{ name: 'Carpet_Carpet_0' }} />
    </group>
  )
}

useGLTF.preload('/models/minimalistic_modern_office.glb')
