/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\mining_quarry.glb --output src\models\QuarryModel.jsx --keepnames --meta --shadows --root public 
Author: 3Dnovator (https://sketchfab.com/cdc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mining-quarry-1c86188613284bf8ae3f9f3f85613769
Title: Mining Quarry
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { modelUrl } from '../lib/assetManifest.js'

const MODEL_URL = modelUrl('quarry')

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Material_0} position={[2.416, -1.541, 3.733]} rotation={[0, Math.PI / 2, 0]} scale={8.439} userData={{ name: 'Object_2' }} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
