/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\vault_01.glb --output src\models\ThresholdVaultModel.jsx --keepnames --meta --shadows --root public 
Author: saeed khalili (https://sketchfab.com/saeedkhalili.ir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vault-01-8269e79d24524e44b5367431f20fdf0a
Title: Vault 01
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { modelUrl } from '../lib/assetManifest.js'

const MODEL_URL = modelUrl('threshold')

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_2" castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Material__25} position={[0, 27.482, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={27.482} userData={{ name: 'Object_2' }} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
