/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\xlist_vault.glb --output src\models\TreasuryVaultModel.jsx --keepnames --meta --shadows --root public 
Author: XList (https://sketchfab.com/xlist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xlist-vault-a3be7371c5694c3b9f5d85184472c005
Title: XList Vault
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { modelUrl } from '../lib/assetManifest.js'

const MODEL_URL = modelUrl('vault')

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)
  return (
    <group {...props} dispose={null}>
      <mesh name="MainVaultInnerDoor_SteelShader_0" castShadow receiveShadow geometry={nodes.MainVaultInnerDoor_SteelShader_0.geometry} material={materials.SteelShader} position={[-0.056, 2.433, -4.565]} rotation={[-Math.PI / 2, 0, 0]} scale={17.791} userData={{ name: 'MainVaultInnerDoor_SteelShader_0' }} />
      <mesh name="MainVault_Lights_0" castShadow receiveShadow geometry={nodes.MainVault_Lights_0.geometry} material={materials.Lights} position={[0, 4.695, -5.195]} rotation={[-Math.PI / 2, 0, 0]} scale={16.936} userData={{ name: 'MainVault_Lights_0' }} />
      <mesh name="Nordin_NordinGold001_0" castShadow receiveShadow geometry={nodes.Nordin_NordinGold001_0.geometry} material={materials['NordinGold.001']} position={[2.174, 0.804, -11.378]} rotation={[-Math.PI / 2, 0, 0]} scale={0.805} userData={{ name: 'Nordin_NordinGold.001_0' }} />
      <mesh name="Circle001_Metal004_0" castShadow receiveShadow geometry={nodes.Circle001_Metal004_0.geometry} material={materials['Metal.004']} position={[-0.062, 1.553, -15.621]} rotation={[-Math.PI / 2, 0, 0]} scale={6.493} userData={{ name: 'Circle.001_Metal.004_0' }} />
      <mesh name="Eagle001_TotemGold002_0" castShadow receiveShadow geometry={nodes.Eagle001_TotemGold002_0.geometry} material={materials['TotemGold.002']} position={[-2.652, 1.853, -21.238]} rotation={[-Math.PI / 2, 0, 0]} scale={1.853} userData={{ name: 'Eagle.001_TotemGold.002_0' }} />
      <mesh name="Cube015_TotemGold004_0" castShadow receiveShadow geometry={nodes.Cube015_TotemGold004_0.geometry} material={materials['TotemGold.004']} position={[-0.129, 0.461, -15.199]} rotation={[-Math.PI / 2, 0, 0]} scale={4.948} userData={{ name: 'Cube.015_TotemGold.004_0' }} />
      <mesh name="Plane_Floor_0" castShadow receiveShadow geometry={nodes.Plane_Floor_0.geometry} material={materials.Floor} position={[-0.03, 0.075, 6.401]} rotation={[-Math.PI / 2, 0, 0]} scale={6.998} userData={{ name: 'Plane_Floor_0' }} />
      <mesh name="Plane001_Walls_0" castShadow receiveShadow geometry={nodes.Plane001_Walls_0.geometry} material={materials.Walls} position={[-0.015, 2.537, 6.012]} rotation={[-Math.PI / 2, 0, 0]} scale={6.657} userData={{ name: 'Plane.001_Walls_0' }} />
      <mesh name="Plane004_ElevatorPlate_0" castShadow receiveShadow geometry={nodes.Plane004_ElevatorPlate_0.geometry} material={materials.ElevatorPlate} position={[0.672, 2.592, 12.648]} rotation={[-Math.PI / 2, 0, 0]} scale={1.297} userData={{ name: 'Plane.004_ElevatorPlate_0' }} />
      <mesh name="Plane005_Celling_0" castShadow receiveShadow geometry={nodes.Plane005_Celling_0.geometry} material={materials.Celling} position={[-0.016, 5.012, 6.012]} rotation={[-Math.PI / 2, 0, 0]} scale={6.657} userData={{ name: 'Plane.005_Celling_0' }} />
      <mesh name="Plane006_ThorFrame_0" castShadow receiveShadow geometry={nodes.Plane006_ThorFrame_0.geometry} material={materials.ThorFrame} position={[-6.329, 2.513, 6.012]} rotation={[-Math.PI / 2, 0, 0]} scale={1.511} userData={{ name: 'Plane.006_ThorFrame_0' }} />
      <mesh name="Plane007_NordinFrame_0" castShadow receiveShadow geometry={nodes.Plane007_NordinFrame_0.geometry} material={materials.NordinFrame} position={[6.284, 3.08, 4.766]} rotation={[-Math.PI / 2, 0, 0]} scale={0.918} userData={{ name: 'Plane.007_NordinFrame_0' }} />
      <mesh name="Plane008_ThorFreya_0" castShadow receiveShadow geometry={nodes.Plane008_ThorFreya_0.geometry} material={materials.ThorFreya} position={[6.284, 1.918, 7.538]} rotation={[-Math.PI / 2, 0, 0]} scale={0.918} userData={{ name: 'Plane.008_ThorFreya_0' }} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
